### PR TITLE
New trick design

### PR DESCRIPTION
**Pull request by hamvocke**
A follow-up to #39 with some tweaks and refactorings. Unfortunately, I can't push to @davidkaufmann's branch since it's created from a fork. So we're going to take Dave's changes and create this new pull request including a few tweaks.

### CODE REVIEW

**Comment by davidkaufmann** [comment]
Small issue I saw in my first game when playing the mobile version:
layout_movement

Haven't done any code-review yet!

**Review by davidkaufmann — CHANGES_REQUESTED** [review]
I totally agree with all changes you suggested in the other PR. Great corrections❗, let's just fix the issue on mobile view I experienced. This should be doable by changing the minheight of the hand to the cardsize in mobile view (the trickstash is lacking, hence the gridview will expand and the gridcenter will 'move' around). Please feel free to implement this the way you think it works best and merge. I'll start working on basic AI aspects of the game 😄
I'm really looking forward to seeing this in production 😁👍🏻

**Comment by hamvocke** [comment]
Good catch. I [fixed](https://github.com/hamvocke/doppelkopf/commit/8ed347f21bf273de197c409339841a04d618f75e) the _collapsing hand_ phenomenon directly in master (since it's rather unrelated to this change). My first hunch was setting a `min-height`, too but I'm sure this is gonna break once we're tweaking the card sizes again in the future. So instead, I opted for rendering an empty "placeholder" card once your hand doesn't hold any more cards. This fills the open space quite nicely (I think), avoids adding a magic-number `min-height` and prevents the hand from collapsing.

**Comment by hamvocke** [comment]
Alright, time to get this in! New trick layout, here we come :partying_face: 

Good job, Dave!

**Pull request merged**
